// <auto-generated />
using System;
using System.Collections.Generic;
using AlertService.Data.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlertService.Data.SQL.Migrations
{
    [DbContext(typeof(AlertDbContext))]
    [Migration("20260929170000_AddAlertTags")]
    partial class AddAlertTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlertService.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("AlertService.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("AlertTags", b =>
                {
                    b.Property<int>("AlertId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("AlertId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("AlertTags", (string)null);
                });

            modelBuilder.Entity("AlertTags", b =>
                {
                    b.HasOne("AlertService.Models.Alert", null)
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlertService.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlertService.Models.Alert", b =>
                {
                    b.HasMany("AlertService.Models.Tag", "Tags")
                        .WithMany("Alerts")
                        .UsingEntity(
                            "AlertTags",
                            r => r.HasOne("AlertService.Models.Tag").WithMany().HasForeignKey("TagId").OnDelete(DeleteBehavior.Cascade).IsRequired(),
                            l => l.HasOne("AlertService.Models.Alert").WithMany().HasForeignKey("AlertId").OnDelete(DeleteBehavior.Cascade).IsRequired(),
                            j =>
                            {
                                j.HasKey("AlertId", "TagId");
                                j.HasIndex("TagId");
                                j.ToTable("AlertTags", (string)null);
                            });

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("AlertService.Models.Tag", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}